"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TokenType = void 0;
var TokenType;
(function (TokenType) {
    TokenType[TokenType["Number"] = 0] = "Number";
    TokenType[TokenType["String"] = 1] = "String";
    TokenType[TokenType["RegularExpression"] = 2] = "RegularExpression";
    TokenType[TokenType["Identifier"] = 3] = "Identifier";
    TokenType[TokenType["OpenParenthesis"] = 4] = "OpenParenthesis";
    TokenType[TokenType["CloseParenthesis"] = 5] = "CloseParenthesis";
    TokenType[TokenType["QuestionMark"] = 6] = "QuestionMark";
    TokenType[TokenType["ShortIfOperator"] = 7] = "ShortIfOperator";
    TokenType[TokenType["Unless"] = 8] = "Unless";
    TokenType[TokenType["ShortUnlessOperator"] = 9] = "ShortUnlessOperator";
    TokenType[TokenType["Loop"] = 10] = "Loop";
    TokenType[TokenType["Colon"] = 11] = "Colon";
    TokenType[TokenType["Comma"] = 12] = "Comma";
    TokenType[TokenType["Dot"] = 13] = "Dot";
    TokenType[TokenType["Declarator"] = 14] = "Declarator";
    TokenType[TokenType["Local"] = 15] = "Local";
    TokenType[TokenType["AssignmentOperator"] = 16] = "AssignmentOperator";
    TokenType[TokenType["BinaryOperator"] = 17] = "BinaryOperator";
    TokenType[TokenType["ArithmeticAssignment"] = 18] = "ArithmeticAssignment";
    TokenType[TokenType["OpenSquareBracket"] = 19] = "OpenSquareBracket";
    TokenType[TokenType["CloseSquareBracket"] = 20] = "CloseSquareBracket";
    TokenType[TokenType["OpenCurlyBracket"] = 21] = "OpenCurlyBracket";
    TokenType[TokenType["CloseCurlyBracket"] = 22] = "CloseCurlyBracket";
    TokenType[TokenType["LogicalOperator"] = 23] = "LogicalOperator";
    TokenType[TokenType["LogicalNot"] = 24] = "LogicalNot";
    TokenType[TokenType["BitwiseNot"] = 25] = "BitwiseNot";
    TokenType[TokenType["BitwiseOperator"] = 26] = "BitwiseOperator";
    TokenType[TokenType["ComparisonOperator"] = 27] = "ComparisonOperator";
    TokenType[TokenType["BinaryOperationAssignment"] = 28] = "BinaryOperationAssignment";
    TokenType[TokenType["TypeOf"] = 29] = "TypeOf";
    TokenType[TokenType["InstanceOf"] = 30] = "InstanceOf";
    TokenType[TokenType["In"] = 31] = "In";
    TokenType[TokenType["Of"] = 32] = "Of";
    TokenType[TokenType["To"] = 33] = "To";
    TokenType[TokenType["Increment"] = 34] = "Increment";
    TokenType[TokenType["Import"] = 35] = "Import";
    TokenType[TokenType["Export"] = 36] = "Export";
    TokenType[TokenType["Await"] = 37] = "Await";
    TokenType[TokenType["AsyncFunction"] = 38] = "AsyncFunction";
    TokenType[TokenType["Function"] = 39] = "Function";
    TokenType[TokenType["Try"] = 40] = "Try";
    TokenType[TokenType["Catch"] = 41] = "Catch";
    TokenType[TokenType["Finally"] = 42] = "Finally";
    TokenType[TokenType["Continue"] = 43] = "Continue";
    TokenType[TokenType["Break"] = 44] = "Break";
    TokenType[TokenType["Return"] = 45] = "Return";
    TokenType[TokenType["QuotationMark"] = 46] = "QuotationMark";
    TokenType[TokenType["RegularExpressionMark"] = 47] = "RegularExpressionMark";
    TokenType[TokenType["Class"] = 48] = "Class";
    TokenType[TokenType["Static"] = 49] = "Static";
    TokenType[TokenType["Get"] = 50] = "Get";
    TokenType[TokenType["Set"] = 51] = "Set";
    TokenType[TokenType["New"] = 52] = "New";
    TokenType[TokenType["Void"] = 53] = "Void";
    TokenType[TokenType["Throw"] = 54] = "Throw";
    TokenType[TokenType["FileEnd"] = 55] = "FileEnd";
})(TokenType || (exports.TokenType = TokenType = {}));
